---
  parser: "babel-eslint"

  ecmaFeatures:
    arrowFunctions: true
    blockBindings: true
    classes: true
    defaultParams: true
    destructuring: true
    forOf: true
    generators: true
    modules: true
    objectLiteralComputedProperties: true
    objectLiteralShorthandMethods: true
    objectLiteralShorthandProperties: true
    restParams: true
    spread: true
    templateStrings: true
    jsx: true

  extends: "airbnb"

  rules:
    comma-dangle:
      - 1
      - "always-multiline"

    object-curly-spacing:
      - 1
      - "never"
